import { Vault } from 'obsidian';

/**
 * Standard SKILL.md frontmatter template.
 * This is the single source of truth for frontmatter fields.
 * Written to <skillsDir>/skill-frontmatter-template.md on plugin load
 * so that skill-creator, skillsmith, and other tools can reference it.
 */
export const FRONTMATTER_TEMPLATE = `---
name: skill-name
description: What this skill does and when to use it
category: uncategorized
version: 1.0.0
disable-model-invocation: false
user-invocable: true
source: local
origin-repo: owner/repo
origin-url: https://github.com/owner/repo
license: MIT
compatibility:
allowed-tools:
---

# Frontmatter Field Reference

This file defines the standard frontmatter fields for SKILL.md files managed by Skills Manager.
All skills in this vault should follow this template. The plugin enforces these fields automatically
when skills are installed.

## Required Fields

| Field | Type | Default | Description |
|-------|------|---------|-------------|
| name | string | (folder name) | Skill identifier, used for display and triggering |
| description | string | — | What the skill does and when to use it. This is the primary trigger mechanism. |

## Standard Fields

| Field | Type | Default | Description |
|-------|------|---------|-------------|
| category | string | uncategorized | Grouping category for the skills manager UI |
| version | string | 1.0.0 | Semantic version of the skill |
| disable-model-invocation | boolean | false | Set to true to disable the skill without removing it |
| user-invocable | boolean | true | Whether the user can invoke this skill directly |

## Source Tracking Fields

| Field | Type | Default | Description |
|-------|------|---------|-------------|
| source | string | local | Installation source: local, github, or zip |
| origin-repo | string | — | GitHub owner/repo if installed from GitHub |
| origin-url | string | — | URL to the original source repository |
| license | string | — | License identifier or reference |

## Optional Fields

| Field | Type | Default | Description |
|-------|------|---------|-------------|
| compatibility | string | — | Environment requirements (target product, system packages, etc.) |
| allowed-tools | string | — | Tool restrictions for the skill |

## Notes

- The \`description\` field should include both what the skill does AND when to use it, since this is what triggers skill activation.
- The \`disable-model-invocation\` field controls whether the skill is active. The plugin toggles this field directly in SKILL.md.
- Fields beyond \`name\` and \`description\` are automatically added by Skills Manager when missing.
- This file is auto-generated by Skills Manager. Do not edit manually.
`;

const TEMPLATE_FILENAME = 'skill-frontmatter-template.md';

/**
 * Write the frontmatter template to the skills directory.
 * Called on plugin load to keep the reference file up to date.
 */
export async function writeFrontmatterTemplate(
  vault: Vault,
  skillsDir: string
): Promise<void> {
  const adapter = vault.adapter;
  const templatePath = `${skillsDir}/${TEMPLATE_FILENAME}`;

  try {
    if (!(await adapter.exists(skillsDir))) return;
    await adapter.write(templatePath, FRONTMATTER_TEMPLATE);
  } catch (e) {
    console.error('[Skills Manager] Failed to write frontmatter template:', e);
  }
}

/**
 * Required frontmatter fields and their defaults.
 * Used by ensureFrontmatter() in installer.ts.
 */
export const REQUIRED_FIELDS: { field: string; defaultValue: string }[] = [
  { field: 'category', defaultValue: 'uncategorized' },
  { field: 'version', defaultValue: '1.0.0' },
  { field: 'disable-model-invocation', defaultValue: 'false' },
  { field: 'user-invocable', defaultValue: 'true' },
];
